exports.toppings = [
    {name: 'PEPPERONI', category: 'MEATS'},
    {name: 'CRUMBLED PEPPERONI', category: 'MEATS'},
    {name: 'NY-STYLE PEPPERONI', category: 'MEATS'},
    {name: 'BEEF', category: 'MEATS'},
    {name: 'BEEF CRUMBLE', category: 'MEATS'},
    {name: 'CHICKEN', category: 'MEATS'},
    {name: 'STEAK', category: 'MEATS'},
    {name: 'SAUSAGE', category: 'MEATS'},
    {name: 'HAM', category: 'MEATS'},
    {name: 'PULLED PORK', category: 'MEATS'},
    {name: 'BRISKET', category: 'MEATS'},
    {name: 'PROSCIUTTO', category: 'MEATS'},
    {name: 'BACON', category: 'MEATS'},
    {name: 'MEATBAALLS', category: 'MEATS'},
    {name: 'ANCHOVIES', category: 'MEATS'},
    {name: 'MUSHROOMS', category: 'VEGGIES'},
    {name: 'ONION', category: 'VEGGIES'},
    {name: 'PINEAPPLE', category: 'VEGGIES'},
    {name: 'TOMATO', category: 'VEGGIES'},
    {name: 'JALAPENO', category: 'VEGGIES'},
    {name: 'SPINACH', category: 'VEGGIES'},
    {name: 'ROASTED PEPPERS', category: 'VEGGIES'},
    {name: 'PICKLES', category: 'VEGGIES'},
    {name: 'CHILLIES', category: 'VEGGIES'},
    {name: 'PICKLED ONION', category: 'VEGGIES'},
    {name: 'GREEN PEPPER', category: 'VEGGIES'},
    {name: 'OLIVES', category: 'VEGGIES'},
    {name: 'BANANA PEPPERS', category: 'VEGGIES'},
    {name: 'BEETS', category: 'VEGGIES'},
    {name: 'SQUASH', category: 'VEGGIES'},
    {name: 'CARMELIZED ONION', category: 'VEGGIES'},
    {name: 'MOZZA', category: 'CHEESE'},
    {name: 'GOAT', category: 'CHEESE'},
    {name: 'FETA', category: 'CHEESE'},
    {name: 'PARMESEAN', category: 'CHEESE'},
    {name: 'CHEDDAR', category: 'CHEESE'},
    {name: 'VEGAN', category: 'CHEESE'},
    {name: 'FIOR DI LATTE', category: 'CHEESE'},
    {name: 'BUFFALO MOZZARELLA', category: 'CHEESE'},
    {name: 'PROVOLONE', category: 'CHEESE'},
    {name: 'MASCARPONE', category: 'CHEESE'},
    {name: 'HONEY', category: 'OTHER'},
    {name: 'BASIL', category: 'OTHER'},
    {name: 'GARLIC', category: 'OTHER'},
    {name: 'LEMON ZEST', category: 'OTHER'},
    {name: 'CILANTRO', category: 'OTHER'},
    {name: 'CHILLI FLAKES', category: 'OTHER'},
    {name: 'OREGANO', category: 'OTHER'},
    {name: 'MUSTARD', category: 'OTHER'},
    {name: 'FRITOS', category: 'OTHER'},
    {name: 'SOUR CREAM', category: 'OTHER'},
    {name: 'RANCH', category: 'OTHER'},
    {name: 'EXTRA VIRGIN OLIVE OIL', category: 'OTHER'},
]

exports.pizzas = [
    {name: 'CLASSIC PEPPERONI', crust: 'CLASSIC', sauce: 'CLASSIC TOMATO', toppings: [{name: 'PEPPERONI', category: 'MEATS'}, {name: 'MOZZA', category: 'CHEESE'}], favourite: false},
    {name: 'CHEESE', crust: 'CLASSIC', sauce: 'CLASSIC TOMATO', toppings: [{name: 'MOZZA', category: 'CHEESE'}], favourite: false}
]